const productData = [
    {
        productId: "p1",
        title: "Clothing",
        name: "Colorfull Pattern Shirts",
        image: "image/product-1-1.jpg",
        imageHover: "image/product-1-2.jpg",
        price: "$238.8",
        lessprice: "$245.8",
        off: "90%",
    },
    {
        productId: "p2",
        title: "Clothing",
        name: "Fish Print Patched T-shirt",
        image: "image/product-2-1.jpg",
        imageHover: "image/product-2-2.jpg",
        price: "$199.9",
        lessprice: "$249.99",
        off: "20%",
    },
    {
        productId: "p3",
        title: "Clothing",
        name: "Vintage Floral Print Dress",
        image: "image/product-3-1.jpg",
        imageHover: "image/product-3-2.jpg",
        price: "$299.9",
        lessprice: "$349.99",
        off: "15%",
    },
    {
        productId: "p4",
        title: "Clothing",
        name: "Stripe Circle Print T-shirt",
        image: "image/product-4-1.jpg",
        imageHover: "image/product-4-2.jpg",
        price: "$149.9",
        lessprice: "$189.99",
        off: "20%",
    },
    {
        productId: "p5",
        title: "Clothing",
        name: "Casual Cotton T-shirt",
        image: "image/product-5-1.jpg",
        imageHover: "image/product-5-2.jpg",
        price: "$129.9",
        lessprice: "$155.99",
        off: "18%",
    },
    {
        productId: "p6",
        title: "Clothing",
        name: "Printed Summer Top",
        image: "image/product-6-1.jpg",
        imageHover: "image/product-6-2.jpg",
        price: "$179.9",
        lessprice: "$199.99",
        off: "10%",
    },
    {
        productId: "p7",
        title: "Clothing",
        name: "Slim Fit Jeans",
        image: "image/product-7-1.jpg",
        imageHover: "image/product-7-2.jpg",
        price: "$249.9",
        lessprice: "$299.99",
        off: "17%",
    },
    {
        productId: "p8",
        title: "Clothing",
        name: "Denim Jacket",
        image: "image/product-8-1.jpg",
        imageHover: "image/product-8-2.jpg",
        price: "$129.9",
        lessprice: "$159.99",
        off: "18%",
    },
    {
        productId: "p9",
        title: "Clothing",
        name: "Casual Sneakers",
        image: "image/product-9-1.jpg",
        imageHover: "image/product-9-2.jpg",
        price: "$99.9",
        lessprice: "$129.99",
        off: "23%",
    },
    {
        productId: "p10",
        title: "Clothing",
        name: "Stylish Pents",
        image: "image/product-10-1.jpg",
        imageHover: "image/product-10-2.jpg",
        price: "$399.9",
        lessprice: "$449.99",
        off: "11%",
    },
    {
        productId: "p11",
        title: "Clothing",
        name: "Cotton T-shirt",
        image: "image/product-11-1.jpg",
        imageHover: "image/product-11-2.jpg",
        price: "$399.9",
        lessprice: "$449.99",
        off: "11%",
    },
    {
        productId: "p12",
        title: "Clothing",
        name: "Stylish Pents",
        image: "image/product-12-1.jpg",
        imageHover: "image/product-12-2.jpg",
        price: "$399.9",
        lessprice: "$449.99",
        off: "11%",
    },
];